import dynamic from "next/dynamic";
import { Roboto  } from "next/font/google";
import "./globals.css";
const Menu = dynamic(() => import("../components/Haeder/Menu"))
const Footer = dynamic(() => import("../components/Footer/Footer"))
const Hero = dynamic(() => import("../components/Hero/Hero"))
// import { BackgroundBeams } from "../components/ui/background-beams";
// const { BackgroundBeams } = dynamic(() => import("../components/ui/background-beams"))
// import { gsapToggle } from "../components/ui/gsapToggle";
import NextTopLoader from 'nextjs-toploader';


const inter = Roboto({
  weight: ['400','500', '700', '900'], 
  subsets: ["latin"] 
});


export const metadata = {
  title: "Harakat®",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/logo-2.png",
      type: "image/png",
    },
  },
  
};

export default function RootLayout({ children }) {
  
  

  return (
    <html lang="en" >
      <body className={`${inter.className} w-full dark:bg-[#f8f8f8] bg-black dark:bg-dot-black/[0.8] bg-dot-white/[0.4] relative transition-all duration-700`} suppressHydrationWarning={true}>
      <NextTopLoader 
      color="#2299DD"
      initialPosition={0.08}
      crawlSpeed={200}
      height={3}
      crawl={true}
      showSpinner={true}
      easing="ease"
      speed={200}
      shadow="0 0 10px #2299DD,0 0 5px #2299DD"
      template='<div class="bar" role="bar"><div class="peg"></div></div> 
      <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
      zIndex={1600}
      showAtBottom={false}
      />
      <div className="absolute transition-all duration-500 pointer-events-none inset-0 flex items-center justify-center dark:bg-[#f8f8f8] bg-black  [mask-image:radial-gradient(ellipse_at_center,transparent_10%,black)]"></div>
        <Menu />
        <Hero />
        {children}
        <Footer />
      </body>
    </html>
  );
}
