import dynamic from "next/dynamic";
import { Roboto  } from "next/font/google";
const Menu = dynamic(() => import("../../components/Haeder/Menu"))
const Footer = dynamic(() => import("../../components/Footer/Footer"))

const inter = Roboto({
  weight: ['400','500', '700', '900'], 
  subsets: ["latin"] 
});


export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/logo-2.png",
      type: "image/png",
    },
  },
  
};

export default function RootLayout({ children }) {
  
  

  return (
    <html lang="en" >
      
      <body className={`${inter.className} w-full bg-black bg-dot-white/[0.4] relative transition-all duration-700`} suppressHydrationWarning={true}>
      <div className="absolute transition-all duration-500 pointer-events-none inset-0 flex items-center justify-center  bg-black  [mask-image:radial-gradient(ellipse_at_center,transparent_10%,black)]"></div>
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
